In [3]:
import pandas as pd
import numpy as np

import networkx as nx
import pickle

from pathlib import Path

from networkx.algorithms.community import louvain_communities

pd.set_option("display.max_columns", None)

In [6]:
from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/MyDrive"

Mounted at /content/drive
'Colab Notebooks'   Dataset   Delhivery_Graph_ETA

In [8]:
!find "/content/drive/MyDrive" -name "logistics_graph.pkl"

/content/drive/MyDrive/Delhivery_Graph_ETA/data/graph_data/logistics_graph.pkl

In [12]:
GRAPH_DIR = Path(
    "/content/drive/MyDrive/Delhivery_Graph_ETA/data/graph_data"
)

with open(GRAPH_DIR / "logistics_graph.pkl", "rb") as f:
    G = pickle.load(f)

In [13]:
def graph_summary(G):

    print("="*50)
    print("GRAPH SUMMARY")
    print("="*50)

    print(f"Nodes   : {G.number_of_nodes():,}")
    print(f"Edges   : {G.number_of_edges():,}")
    print(f"Density : {nx.density(G):.6f}")

    print(
        f"Weak Components   : "
        f"{nx.number_weakly_connected_components(G)}"
    )

    print(
        f"Strong Components : "
        f"{nx.number_strongly_connected_components(G)}"
    )

graph_summary(G)

==================================================
GRAPH SUMMARY
==================================================
Nodes   : 1,657
Edges   : 2,783
Density : 0.001014
Weak Components   : 64
Strong Components : 545

In [15]:
degree_centrality = nx.degree_centrality(G)

in_degree_centrality = nx.in_degree_centrality(G)

out_degree_centrality = nx.out_degree_centrality(G)

In [16]:
betweenness = nx.betweenness_centrality(
    G,
    normalized=True
)

In [17]:
closeness = nx.closeness_centrality(G)

In [18]:
pagerank = nx.pagerank(
    G,
    alpha=0.85
)

HITS

In [19]:
hub_scores, authority_scores = nx.hits(
    G,
    max_iter=1000,
    normalized=True
)

In [20]:
G_undirected = G.to_undirected()

Louvain

In [21]:
communities = louvain_communities(
    G_undirected,
    seed=42
)

Community table

In [22]:
community_rows = []

for idx, community in enumerate(communities):

    size = len(community)

    for node in community:

        community_rows.append(
            {
                "facility": node,
                "community_id": idx,
                "community_size": size
            }
        )

community_df = pd.DataFrame(community_rows)

community_df.head()

       facility  community_id  community_size
0  IND673027AAB             0              43
1  IND679531AAA             0              43
2  IND686028AAB             0              43
3  IND683572AAA             0              43
4  IND670643AAA             0              43

Centrality table

In [23]:
centrality_df = pd.DataFrame({
    "facility": list(G.nodes()),

    "degree_centrality":
        [degree_centrality[n] for n in G.nodes()],

    "in_degree_centrality":
        [in_degree_centrality[n] for n in G.nodes()],

    "out_degree_centrality":
        [out_degree_centrality[n] for n in G.nodes()],

    "betweenness_centrality":
        [betweenness[n] for n in G.nodes()],

    "closeness_centrality":
        [closeness[n] for n in G.nodes()],

    "pagerank":
        [pagerank[n] for n in G.nodes()],

    "hub_score":
        [hub_scores[n] for n in G.nodes()],

    "authority_score":
        [authority_scores[n] for n in G.nodes()]
})

Graph feature store

In [24]:
graph_feature_store = centrality_df.merge(
    community_df,
    on="facility",
    how="left"
)

In [25]:
graph_feature_store.isna().sum()

facility                  0
degree_centrality         0
in_degree_centrality      0
out_degree_centrality     0
betweenness_centrality    0
closeness_centrality      0
pagerank                  0
hub_score                 0
authority_score           0
community_id              0
community_size            0
dtype: int64

In [26]:
assert len(graph_feature_store) == G.number_of_nodes()

In [27]:
assert graph_feature_store["facility"].nunique() \
       == len(graph_feature_store)

In [28]:
community_df["facility"].nunique()

1657

Degree

In [29]:
graph_feature_store.nlargest(
    20,
    "degree_centrality"
)

,facility,degree_centrality,in_degree_centrality,out_degree_centrality,betweenness_centrality,closeness_centrality,pagerank,hub_score,authority_score,community_id,community_size
25,IND000000ACB,0.056763,0.027174,0.029589,0.220228,0.183963,0.011424,4.491250e-02,3.436966e-02,1,122
12,IND562132AAA,0.042874,0.021739,0.021135,0.124943,0.171499,0.009635,3.091717e-02,2.874694e-02,60,109
24,IND160002AAC,0.036836,0.019324,0.017512,0.055078,0.153548,0.008052,1.764368e-02,1.479417e-02,10,83
61,IND421302AAG,0.035024,0.017512,0.017512,0.069625,0.167048,0.006190,2.925008e-02,2.437871e-02,7,58
64,IND501359AAE,0.034420,0.018116,0.016304,0.092632,0.166713,0.008798,2.005699e-02,2.161935e-02,53,98
67,IND712311AAA,0.027778,0.014493,0.013285,0.090659,0.168480,0.006547,1.210561e-02,1.828587e-02,75,64
102,IND110037AAM,0.027174,0.012681,0.014493,0.041331,0.154629,0.004855,1.939823e-02,1.435324e-02,1,122
1,IND411033AAA,0.025966,0.013889,0.012077,0.043254,0.161800,0.006174,1.720226e-02,1.917142e-02,37,64
47,IND131028AAB,0.024155,0.012077,0.012077,0.047837,0.156051,0.005777,8.606813e-03,1.631954e-02,15,71
66,IND600056AAB,0.021739,0.010870,0.010870,0.042146,0.155466,0.004529,7.809165e-03,1.047736e-02,60,109
110,IND781018AAB,0.019324,0.010266,0.009058,0.044542,0.147279,0.004665,4.045421e-03,4.612194e-03,82,67
59,IND382430AAB,0.018116,0.010266,0.007850,0.031695,0.150515,0.003816,5.193531e-03,1.105111e-02,28,49
52,IND209304AAA,0.017512,0.009662,0.007850,0.040359,0.151862,0.005098,6.106367e-03,9.326770e-03,1,122
1022,IND560099AAB,0.017512,0.006643,0.010870,0.003475,0.138433,0.002242,1.085833e-02,7.738764e-03,60,109
71,IND842001AAA,0.016304,0.007246,0.009058,0.024699,0.146413,0.004581,3.472427e-05,5.515929e-03,92,25
15,IND000000ACA,0.013285,0.007850,0.005435,0.008060,0.125750,0.002895,2.417837e-03,2.863165e-03,10,83
62,IND462022AAA,0.013285,0.007850,0.005435,0.029638,0.159997,0.004297,4.993664e-03,1.498587e-02,44,42
93,IND400072AAB,0.013285,0.006643,0.006643,0.005097,0.138561,0.001784,7.377147e-03,7.137249e-03,7,58
435,IND302014AAB,0.012681,0.005435,0.007246,0.000103,0.005288,0.003014,1.174393e-19,1.381733e-19,20,20
991,IND530012AAA,0.012681,0.006039,0.006643,0.017799,0.134760,0.002962,4.402508e-03,1.850616e-03,58,25

Betweeness

In [30]:
graph_feature_store.nlargest(
    20,
    "betweenness_centrality"
)

,facility,degree_centrality,in_degree_centrality,out_degree_centrality,betweenness_centrality,closeness_centrality,pagerank,hub_score,authority_score,community_id,community_size
25,IND000000ACB,0.056763,0.027174,0.029589,0.220228,0.183963,0.011424,0.044913,0.034370,1,122
12,IND562132AAA,0.042874,0.021739,0.021135,0.124943,0.171499,0.009635,0.030917,0.028747,60,109
64,IND501359AAE,0.034420,0.018116,0.016304,0.092632,0.166713,0.008798,0.020057,0.021619,53,98
67,IND712311AAA,0.027778,0.014493,0.013285,0.090659,0.168480,0.006547,0.012106,0.018286,75,64
61,IND421302AAG,0.035024,0.017512,0.017512,0.069625,0.167048,0.006190,0.029250,0.024379,7,58
24,IND160002AAC,0.036836,0.019324,0.017512,0.055078,0.153548,0.008052,0.017644,0.014794,10,83
47,IND131028AAB,0.024155,0.012077,0.012077,0.047837,0.156051,0.005777,0.008607,0.016320,15,71
110,IND781018AAB,0.019324,0.010266,0.009058,0.044542,0.147279,0.004665,0.004045,0.004612,82,67
1,IND411033AAA,0.025966,0.013889,0.012077,0.043254,0.161800,0.006174,0.017202,0.019171,37,64
66,IND600056AAB,0.021739,0.010870,0.010870,0.042146,0.155466,0.004529,0.007809,0.010477,60,109
102,IND110037AAM,0.027174,0.012681,0.014493,0.041331,0.154629,0.004855,0.019398,0.014353,1,122
56,IND302014AAA,0.010870,0.006039,0.004831,0.040490,0.155143,0.002901,0.006163,0.008975,22,73
52,IND209304AAA,0.017512,0.009662,0.007850,0.040359,0.151862,0.005098,0.006106,0.009327,1,122
59,IND382430AAB,0.018116,0.010266,0.007850,0.031695,0.150515,0.003816,0.005194,0.011051,28,49
62,IND462022AAA,0.013285,0.007850,0.005435,0.029638,0.159997,0.004297,0.004994,0.014986,44,42
71,IND842001AAA,0.016304,0.007246,0.009058,0.024699,0.146413,0.004581,0.000035,0.005516,92,25
76,IND683511AAA,0.012077,0.007850,0.004227,0.022769,0.138638,0.002969,0.003251,0.005138,0,43
68,IND751002AAB,0.011473,0.007850,0.003623,0.021587,0.162575,0.002846,0.005323,0.013295,79,29
1631,IND854326AAB,0.009662,0.004831,0.004831,0.018994,0.120826,0.001853,0.003930,0.000025,93,15
991,IND530012AAA,0.012681,0.006039,0.006643,0.017799,0.134760,0.002962,0.004403,0.001851,58,25

Pagerank

In [31]:
graph_feature_store.nlargest(
    20,
    "pagerank"
)

,facility,degree_centrality,in_degree_centrality,out_degree_centrality,betweenness_centrality,closeness_centrality,pagerank,hub_score,authority_score,community_id,community_size
25,IND000000ACB,0.056763,0.027174,0.029589,0.220228,0.183963,0.011424,4.491250e-02,3.436966e-02,1,122
12,IND562132AAA,0.042874,0.021739,0.021135,0.124943,0.171499,0.009635,3.091717e-02,2.874694e-02,60,109
64,IND501359AAE,0.034420,0.018116,0.016304,0.092632,0.166713,0.008798,2.005699e-02,2.161935e-02,53,98
24,IND160002AAC,0.036836,0.019324,0.017512,0.055078,0.153548,0.008052,1.764368e-02,1.479417e-02,10,83
67,IND712311AAA,0.027778,0.014493,0.013285,0.090659,0.168480,0.006547,1.210561e-02,1.828587e-02,75,64
61,IND421302AAG,0.035024,0.017512,0.017512,0.069625,0.167048,0.006190,2.925008e-02,2.437871e-02,7,58
1,IND411033AAA,0.025966,0.013889,0.012077,0.043254,0.161800,0.006174,1.720226e-02,1.917142e-02,37,64
47,IND131028AAB,0.024155,0.012077,0.012077,0.047837,0.156051,0.005777,8.606813e-03,1.631954e-02,15,71
52,IND209304AAA,0.017512,0.009662,0.007850,0.040359,0.151862,0.005098,6.106367e-03,9.326770e-03,1,122
102,IND110037AAM,0.027174,0.012681,0.014493,0.041331,0.154629,0.004855,1.939823e-02,1.435324e-02,1,122
110,IND781018AAB,0.019324,0.010266,0.009058,0.044542,0.147279,0.004665,4.045421e-03,4.612194e-03,82,67
71,IND842001AAA,0.016304,0.007246,0.009058,0.024699,0.146413,0.004581,3.472427e-05,5.515929e-03,92,25
66,IND600056AAB,0.021739,0.010870,0.010870,0.042146,0.155466,0.004529,7.809165e-03,1.047736e-02,60,109
62,IND462022AAA,0.013285,0.007850,0.005435,0.029638,0.159997,0.004297,4.993664e-03,1.498587e-02,44,42
1231,IND625008AAA,0.004831,0.003019,0.001812,0.000053,0.004586,0.003881,-3.599521e-21,6.244880e-20,67,28
59,IND382430AAB,0.018116,0.010266,0.007850,0.031695,0.150515,0.003816,5.193531e-03,1.105111e-02,28,49
683,IND580028AAA,0.010266,0.005435,0.004831,0.013632,0.138896,0.003565,6.232982e-03,5.644377e-03,34,40
351,IND244901AAB,0.010266,0.006039,0.004227,0.014031,0.107672,0.003560,9.629016e-20,5.271334e-19,15,71
435,IND302014AAB,0.012681,0.005435,0.007246,0.000103,0.005288,0.003014,1.174393e-19,1.381733e-19,20,20
76,IND683511AAA,0.012077,0.007850,0.004227,0.022769,0.138638,0.002969,3.251047e-03,5.137507e-03,0,43

In [32]:
OUTPUT_DIR = GRAPH_DIR

centrality_df.to_csv(
    OUTPUT_DIR / "node_centrality_features.csv",
    index=False
)

community_df.to_csv(
    OUTPUT_DIR / "community_features.csv",
    index=False
)

graph_feature_store.to_csv(
    OUTPUT_DIR / "graph_feature_store.csv",
    index=False
)

In [33]:
nx.betweenness_centrality(
    G,
    k=500,
    seed=42
)

{'IND000000AAL': 0.0,
 'IND411033AAA': 0.04215679604516998,
 'IND000000AAQ': 0.0,
 'IND700028AAB': 0.0,
 'IND000000AAS': 0.004648572068608516,
 'IND783370AAC': 0.005574622356495469,
 'IND000000AAZ': 0.0008003923254363712,
 'IND444203AAA': 0.001336812598005679,
 'IND444303AAA': 0.0,
 'IND000000ABA': 0.00040120845921450156,
 'IND683565AAA': 0.0,
 'IND000000ABD': 0.0,
 'IND562132AAA': 0.1263910565028428,
 'IND000000ABG': 0.0,
 'IND501359AAF': 0.0,
 'IND000000ACA': 0.008918429003021148,
 'IND140406AAA': 0.00019979536111497918,
 'IND142001AAB': 0.0011786505538771402,
 'IND142401AAA': 0.0,
 'IND143001AAA': 0.0,
 'IND144001AAB': 0.005596374622356496,
 'IND144514AAA': 0.0004,
 'IND147301AAA': 0.00019939577039274927,
 'IND152026AAA': 0.004678036839035574,
 'IND160002AAC': 0.056826692110491725,
 'IND000000ACB': 0.21582305503794372,
 'IND000000AEL': 0.0,
 'IND110024AAA': 0.00040120845921450156,
 'IND110030AAD': 0.0,
 'IND110037AAK': 0.0,
 'IND110043AAA': 0.0017388250821885464,
 'IND110043AAC': 0.0,
 'IND110052AAA': 0.0,
 'IND110064AAA': 0.0008024169184290031,
 'IND110085AAB': 0.0029353474320241695,
 'IND110092AAC': 0.00040120845921450156,
 'IND110095AAB': 0.0,
 'IND121002AAB': 0.0,
 'IND121004AAB': 0.0033840939231805293,
 'IND122001AAA': 0.0012512489891346264,
 'IND122015AAC': 0.0,
 'IND124103AAA': 0.0,
 'IND124112AAA': 0.0,
 'IND125001AAA': 0.010226669389580306,
 'IND125005AAA': 0.0045139577039274925,
 'IND125033AAA': 0.0,
 'IND127021AAA': 0.0008012084592145016,
 'IND131028AAB': 0.04875290224812179,
 'IND201001AAC': 4.884417951538872e-05,
 'IND201007AAA': 0.0034638411739318104,
 'IND201301AAF': 0.0016153152225901954,
 'IND201301AAM': 0.0,
 'IND209304AAA': 0.03747282588707162,
 'IND282002AAD': 0.004329133740521178,
 'IND301001AAB': 0.005596086432684099,
 'IND301705AAA': 0.0012000000000000001,
 'IND302014AAA': 0.04010193751210965,
 'IND302022AAD': 0.0,
 'IND328001AAA': 1.7991675997718297e-05,
 'IND382430AAB': 0.030736892463025363,
 'IND390022AAA': 0.0021029938138397387,
 'IND421302AAG': 0.07017500564828018,
 'IND462022AAA': 0.025865595724501075,
 'IND474003AAA': 0.0050495468277945614,
 'IND501359AAE': 0.08540883974557832,
 'IND521225AAB': 0.010205748859249212,
 'IND600056AAB': 0.038331553179952,
 'IND712311AAA': 0.09160259286965486,
 'IND751002AAB': 0.021895611504102252,
 'IND821115AAB': 0.009416227880880451,
 'IND834002AAB': 0.010141055963170765,
 'IND842001AAA': 0.028421148036253778,
 'IND000000ACK': 0.0,
 'IND000000ACN': 0.0,
 'IND000000ACT': 0.0,
 'IND000000ADM': 0.0,
 'IND683511AAA': 0.024685196374622357,
 'IND000000ADV': 0.0,
 'IND600044AAC': 0.0,
 'IND000000AEM': 0.0,
 'IND110037AAB': 0.0,
 'IND110064AAB': 0.0,
 'IND000000AET': 0.0050392749244713,
 'IND000000AFF': 0.0,
 'IND734203AAA': 0.0,
 'IND000000AFG': 0.0,
 'IND673027AAB': 2.4169184290030213e-06,
 'IND673632AAA': 0.0040386706948640485,
 'IND000000AFJ': 1.2108809764544194e-06,
 'IND695121AAA': 0.0006761329305135952,
 'IND695572AAB': 0.0006774879063262476,
 'IND000000AFR': 0.0,
 'IND000000AFT': 0.004534138972809668,
 'IND400072AAB': 0.004452815729417268,
 'IND400701AAA': 0.0008012084592145016,
 'IND400706AAA': 0.0,
 'IND410206AAA': 0.0,
 'IND410206AAB': 0.0,
 'IND410209AAA': 0.0,
 'IND410210AAA': 0.0,
 'IND110014AAA': 0.0,
 'IND110020AAB': 0.0,
 'IND110037AAM': 0.04353037111783735,
 'IND110035AAC': 0.0,
 'IND201301AAD': 0.0,
 'IND202001AAB': 0.003683412458639048,
 'IND226004AAC': 0.0,
 'IND250002AAC': 0.0,
 'IND282001AAA': 0.0,
 'IND282001AAC': 0.0,
 'IND781018AAB': 0.049397793156863386,
 'IND811399AAA': 0.00026788088044885615,
 'IND110039AAA': 0.0,
 'IND110078AAA': 0.0,
 'IND110044AAB': 0.002651829338435179,
 'IND110005AAA': 0.0,
 'IND110046AAA': 0.0,
 'IND110077AAA': 0.0,
 'IND110083AAA': 0.0,
 'IND110085AAA': 0.0,
 'IND110087AAA': 0.0,
 'IND110093AAA': 0.0,
 'IND121001AAA': 0.0,
 'IND121002AAA': 0.0,
 'IND121004AAA': 0.0,
 'IND121004AAC': 0.0,
 'IND121102AAA': 0.0,
 'IND122001AAD': 0.0,
 'IND122050AAA': 0.0,
 'IND122101AAC': 0.0,
 'IND122001AAJ': 0.0007991814444599167,
 'IND507123AAA': 0.0017376142012120914,
 'IND122002AAD': 0.0,
 'IND122503AAA': 0.0,
 'IND122004AAA': 0.0,
 'IND122413AAE': 0.0,
 'IND123001AAA': 0.0021353474320241696,
 'IND123401AAB': 0.001734138972809668,
 'IND123106AAB': 0.0,
 'IND124001AAB': 0.0011963504047369663,
 'IND126102AAA': 0.0021347831614891414,
 'IND124141AAA': 0.0,
 'IND124507AAA': 0.0004008016032064128,
 'IND131028AAE': 0.0,
 'IND125047AAB': 0.0004072507552870091,
 'IND125051AAA': 0.0021372049234420504,
 'IND335501AAA': 0.0004008016032064128,
 'IND335513AAA': 0.005461027190332326,
 'IND335523AAB': 5.577391164274901e-06,
 'IND335524AAA': 0.0,
 'IND125050AAA': 0.0,
 'IND125111AAA': 0.003068277945619336,
 'IND125104AAA': 0.002656193353474319,
 'IND125121AAA': 0.0026670694864048346,
 'IND126116AAA': 0.0,
 'IND131301AAA': 0.004002416918429003,
 'IND126112AAA': 0.0,
 'IND127201AAA': 0.0004,
 'IND131021AAA': 0.0,
 'IND131028AAA': 0.0,
 'IND132103AAA': 0.0008,
 'IND136118AAA': 0.0012060374525486018,
 'IND201204AAA': 0.0,
 'IND244001AAA': 0.0035418268561291768,
 'IND244235AAA': 0.007127245427410713,
 'IND247667AAA': 0.0,
 'IND247667AAB': 0.0,
 'IND248001AAA': 0.0013392343599585878,
 'IND248001AAD': 0.0,
 'IND249407AAA': 0.0020060422960725076,
 'IND250002AAA': 0.0,
 'IND250609AAA': 0.0,
 'IND250611AAA': 0.0008024169184290031,
 'IND251001AAA': 0.00040120845921450156,
 'IND132001AAA': 0.0004006042296072508,
 'IND132103AAB': 0.0,
 'IND133004AAA': 0.0,
 'IND135001AAA': 0.00040120845921450156,
 'IND134102AAA': 0.0,
 'IND174103AAA': 0.0013353474320241692,
 'IND134109AAA': 0.0,
 'IND134203AAA': 0.00040120845921450156,
 'IND140501AAA': 0.0,
 'IND173025AAA': 0.0,
 'IND136027AAA': 0.00040362537764350453,
 'IND132039AAA': 0.0,
 'IND136128AAA': 0.0008064467303186433,
 'IND140001AAA': 0.00040120845921450156,
 'IND140118AAA': 0.0,
 'IND140301AAA': 0.0008016032064128256,
 'IND140901AAA': 0.0013329305135951661,
 'IND140401AAA': 0.001338023478982133,
 'IND160055AAA': 0.0,
 'IND141003AAB': 0.0,
 'IND141109AAA': 0.0,
 'IND142026AAA': 0.0,
 'IND141010AAA': 0.0,
 'IND141115AAA': 0.0013365558912386704,
 'IND151001AAA': 0.007725420629779195,
 'IND144001AAA': 0.0,
 'IND144040AAA': 0.0,
 'IND144401AAB': 0.0,
 'IND144601AAA': 0.0008012084592145016,
 'IND144001AAC': 0.0,
 'IND144527AAA': 0.0,
 'IND145001AAA': 0.0,
 'IND176201AAA': 0.0,
 'IND176303AAA': 2.4169184290030213e-06,
 'IND147001AAB': 0.0002,
 'IND147201AAA': 0.0,
 'IND147001AAD': 0.0014028056112224449,
 'IND148023AAA': 0.0008048338368580061,
 'IND147101AAA': 0.0,
 'IND147105AAA': 0.0,
 'IND148001AAA': 0.0,
 'IND148024AAB': 0.0,
 'IND148028AAA': 0.0,
 'IND148101AAA': 0.0004008016032064128,
 'IND148102AAA': 0.0013353474320241692,
 'IND151103AAA': 0.0,
 'IND151302AAA': 0.0007987915407854985,
 'IND151505AAA': 0.00039959072222995836,
 'IND151506AAA': 0.0013380234789821333,
 'IND152024AAA': 0.00039959072222995836,
 'IND152123AAA': 0.0013380234789821333,
 'IND152101AAA': 0.0,
 'IND152107AAA': 0.0,
 'IND152116AAA': 0.0,
 'IND140603AAA': 0.0,
 'IND160003AAA': 0.0,
 'IND160102AAC': 0.0,
 'IND173212AAA': 0.0008012084592145016,
 'IND174001AAA': 0.0012024169184290032,
 'IND174307AAA': 0.0,
 'IND176041AAA': 0.0,
 'IND181152AAA': 0.00019939577039274927,
 'IND184104AAA': 0.000998976805574896,
 'IND160102AAD': 0.0,
 'IND160002AAD': 0.0,
 'IND173220AAA': 0.0,
 'IND175018AAA': 0.0008012084592145016,
 'IND174021AAA': 0.0,
 'IND176048AAA': 0.0,
 'IND174101AAB': 0.0,
 'IND175001AAA': 0.0004,
 'IND175101AAA': 0.0,
 'IND175015AAA': 0.0,
 'IND176061AAA': 0.0,
 'IND176110AAB': 0.0,
 'IND177033AAA': 0.0,
 'IND176215AAA': 0.0,
 'IND176310AAA': 1.2084592145015106e-06,
 'IND177001AAA': 0.0,
 'IND177101AAA': 0.0,
 'IND176001AAA': 0.0,
 'IND176001AAB': 0.0,
 'IND177203AAA': 0.0,
 'IND184121AAA': 0.0,
 'IND181152AAB': 0.00040120845921450156,
 'IND181201AAB': 0.0,
 'IND201001AAA': 0.0,
 'IND201005AAA': 0.0,
 'IND201007AAB': 0.0014631420804492024,
 'IND245101AAA': 0.0,
 'IND245304AAA': 0.0,
 'IND201301AAL': 0.0004072507552870091,
 'IND201304AAA': 0.0,
 'IND203205AAA': 0.0,
 'IND201307AAA': 0.0,
 'IND201306AAA': 0.0,
 'IND205001AAB': 0.0049270746931930325,
 'IND207123AAA': 0.0,
 'IND202001AAC': 0.0,
 'IND204215AAA': 0.0,
 'IND203001AAA': 0.0,
 'IND203131AAA': 0.0,
 'IND203135AAA': 8.459214501510575e-06,
 'IND203390AAA': 6.042296072507553e-06,
 'IND203396AAB': 0.0,
 'IND204101AAA': 1.0538065316249447e-05,
 'IND207001AAA': 0.0,
 'IND205135AAA': 0.0,
 'IND209625AAA': 0.0033353474320241693,
 'IND209721AAB': 0.0,
 'IND283203AAA': 9.264853977844916e-06,
 'IND206001AAA': 0.0,
 'IND206122AAA': 0.0004,
 'IND207302AAA': 0.0,
 'IND207247AAB': 0.0013293051359516616,
 'IND208006AAA': 0.0,
 'IND208012AAA': 0.0,
 'IND208017AAA': 0.0,
 'IND208019AAA': 0.0,
 'IND209101AAA': 0.0016012084592145015,
 'IND209111AAA': 0.0012000000000000001,
 'IND285001AAD': 0.0007987915407854985,
 'IND209206AAB': 0.00040120845921450156,
 'IND210301AAA': 0.0,
 'IND209801AAA': 0.0,
 'IND211002AAB': 0.0074465256797583085,
 'IND212601AAA': 0.0008,
 'IND221313AAA': 0.008826586102719034,
 'IND241124AAB': 0.0029341389728096677,
 'IND210001AAA': 0.0004008016032064128,
 'IND210427AAA': 0.0013353474320241694,
 'IND210431AAA': 0.0013380234789821337,
 'IND210501AAB': 0.0,
 'IND211011AAA': 0.0008012084592145016,
 'IND211013AAA': 0.0,
 'IND485001AAC': 0.0028090634441087616,
 'IND211008AAA': 0.0,
 'IND211010AAB': 0.0,
 'IND212501AAA': 0.0004,
 'IND212402AAA': 0.0,
 'IND221010AAA': 0.00040120845921450156,
 'IND221005A1A': 0.0,
 'IND221010AAB': 0.002823774437091706,
 'IND222001AAA': 4.843523905817677e-06,
 'IND232101AAB': 0.004425769968940903,
 'IND233001AAA': 0.002018126888217523,
 'IND221303AAA': 0.00040241691842900305,
 'IND231001AAA': 0.0,
 'IND221401AAA': 0.0008040249683657345,
 'IND222136AAA': 0.0,
 'IND276128AAA': 0.0012036253776435046,
 'IND221706AAA': 0.0027021148036253783,
 'IND273014AAB': 0.005412637964751256,
 'IND222125AAB': 2.4217619529088387e-06,
 'IND223101AAB': 0.0004048338368580061,
 'IND224001AAA': 0.0,
 'IND224141AAB': 0.0,
 'IND224122AAA': 0.0,
 'IND226004AAA': 0.0,
 'IND226016AAA': 0.0,
 'IND226024AAA': 0.0,
 'IND231205AAA': 0.0,
 'IND231216AAA': 0.0,
 'IND231208AAA': 0.0,
 'IND231217AAA': 6.054404882272096e-06,
 'IND231225AAB': 9.667673716012085e-06,
 'IND486886AAA': 7.265285858726516e-06,
 'IND232104AAB': 0.004027794561933535,
 'IND232327AAA': 0.0,
 'IND233221AAC': 0.0,
 'IND275101AAA': 0.0,
 'IND275503AAA': 0.0012108761329305137,
 'IND242001AAA': 0.0025329305135951665,
 'IND242307AAB': 0.002131722054380665,
 'IND242221AAA': 0.0,
 'IND243001AAA': 0.0,
 'IND243503AAB': 0.0,
 'IND244901AAB': 0.013384894259818732,
 'IND243002AAA': 0.0,
 'IND243201AAA': 0.00040120845921450156,
 'IND262001AAA': 0.00040120845921450156,
 'IND243301AAB': 0.00040120845921450156,
 'IND244901AAC': 0.0,
 'IND263153AAB': 0.01248036253776435,
 'IND244221AAA': 0.006578851963746224,
 'IND244301AAA': 0.0012036253776435046,
 'IND244412AAA': 0.0008024169184290031,
 'IND244501AAA': 0.0,
 'IND244601AAB': 0.0,
 'IND244713AAA': 6.042296072507553e-07,
 'IND244715AAA': 0.0,
 'IND263401AAA': 0.0,
 'IND244921AAB': 0.00040120845921450156,
 'IND246725AAB': 0.001997953611149792,
 'IND246001AAA': 0.0,
 'IND249201AAA': 0.0012036253776435046,
 'IND246149AAA': 0.0,
 'IND246174AAA': 0.0008024169184290031,
 'IND246444AAB': 0.00040120845921450156,
 'IND246424AAA': 0.0,
 'IND246701AAA': 0.002929305135951662,
 'IND246763AAA': 0.0025343738837190996,
 'IND246761AAA': 0.0008012084592145016,
 'IND247554AAA': 0.0,
 'IND247776AAA': 0.00040120845921450156,
 'IND251309AAB': 0.0,
 'IND248122AAB': 0.0,
 'IND248197AAA': 0.0,
 'IND250221AAA': 0.0,
 'IND251201AAA': 0.0,
 'IND261001AAA': 0.0,
 'IND262701AAA': 0.0,
 'IND261201AAB': 0.0,
 'IND262122AAB': 0.0,
 'IND262405AAA': 0.0,
 'IND262501AAA': 0.0013362071575174518,
 'IND262802AAA': 0.0,
 'IND262723AAB': 0.0,
 'IND263002AAA': 0.0,
 'IND263645AAA': 0.002133572280512687,
 'IND263139AAA': 0.0,
 'IND263601AAA': 0.0013362071575174518,
 'IND271001AAA': 0.0,
 'IND271201AAA': 0.0,
 'IND271210AAA': 0.0,
 'IND272001AAA': 0.0,
 'IND272175AAA': 0.0,
 'IND272155AAA': 0.0,
 'IND272207AAB': 0.0,
 'IND272153AAC': 0.0,
 'IND273155AAA': 6.042296072507553e-06,
 'IND273304AAA': 0.0,
 'IND274001AAA': 2.175226586102719e-05,
 'IND274301AAB': 0.0013537649316760411,
 'IND277303AAC': 1.2108809764544193e-05,
 'IND273303AAA': 0.0,
 'IND274509AAB': 1.570996978851964e-05,
 'IND274304AAA': 2.4217619529088387e-06,
 'IND274304AAB': 0.0013522658610271908,
 'IND274402AAA': 2.4169184290030213e-06,
 'IND275303AAA': 0.0008072507552870091,
 'IND276140AAA': 0.00040362537764350453,
 'IND276305AAA': 0.0008040249683657345,
 'IND276129AAA': 0.0,
 'IND277201AAA': 0.0013573975746054045,
 'IND277211AAA': 0.0013595166163141998,
 'IND281121AAB': 0.0,
 'IND281401AAA': 0.0,
 'IND321022AAA': 0.0,
 'IND282001AAF': 0.0,
 'IND283122AAB': 0.0,
 'IND281004AAA': 0.0,
 'IND282005AAA': 0.0,
 'IND284001AAA': 0.0,
 'IND284403AAA': 0.0,
 'IND472001AAA': 0.0,
 'IND285205AAB': 0.00039959072222995836,
 'IND321001AAB': 0.0005981752023684831,
 'IND321606AAA': 0.00020100624209143362,
 'IND301019AAA': 0.0,
 'IND302004AAA': 1.0876132930513596e-05,
 'IND302014AAB': 0.00015862540791552893,
 'IND302033AAB': 0.0,
 'IND302006AAA': 0.0,
 'IND302006AAC': 0.0,
 'IND303702AAB': 0.0037794561933534743,
 'IND305001AAC': 0.0074505506481240425,
 'IND306401AAB': 0.010200906344410877,
 'IND313001AAB': 0.008717341389728097,
 'IND332404AAA': 0.0037794561933534743,
 'IND302020AAA': 0.0,
 'IND302023AAA': 0.0,
 'IND302026AAA': 0.0,
 'IND303008AAB': 4.843523905817677e-06,
 'IND303301AAB': 0.0,
 'IND303303AAA': 3.0272024411360483e-05,
 'IND303603AAB': 2.5377643504531723e-05,
 'IND303901AAA': 0.0,
 'IND304001AAA': 3.0211480362537768e-05,
 'IND303002AAA': 0.0,
 'IND303338AAB': 2.175226586102719e-05,
 'IND303106AAA': 0.0013416561219114966,
 'IND303108AAB': 0.0,
 'IND322230AAA': 4.3591715152359095e-05,
 'IND303503AAA': 0.0,
 'IND332001AAB': 0.009825981873111784,
 'IND322001AAC': 2.058497659972513e-05,
 'IND305802AAA': 0.0016048338368580062,
 'IND305901AAA': 0.0011963746223564956,
 'IND342602AAC': 0.0008012084592145016,
 'IND305404AAA': 0.0030682779456193353,
 'IND305601AAC': 0.0,
 'IND305624AAA': 0.00213720492344205,
 'IND341512AAA': 0.0012036253776435046,
 'IND306116AAA': 0.00040201248418286723,
 'IND306001AAA': 0.0,
 'IND306304AAB': 0.0,
 'IND311302AAA': 0.0,
 'IND342005AAD': 0.0032096676737160125,
 'IND343001AAA': 0.0020060422960725076,
 'IND306902AAA': 0.0008024169184290031,
 'IND307001AAA': 0.0012036253776435046,
 'IND311001AAA': 0.0017339815582827285,
 'IND313324AAA': 0.0026658610271903323,
 'IND311301AAA': 0.0,
 'IND312001AAA': 0.0025353474320241693,
 'IND312601AAA': 0.0008012084592145016,
 'IND312403AAA': 0.0,
 'IND458664AAA': 0.0004,
 'IND312605AAB': 0.0021341389728096677,
 'IND458001AAB': 0.0004008016032064128,
 'IND327001AAB': 0.0012000000000000001,
 'IND321001AAA': 0.00133595166163142,
 'IND321401AAB': 0.0,
 'IND321408AAB': 0.0,
 'IND322201AAA': 6.888217522658611e-05,
 'IND322241AAA': 5.691140589335771e-05,
 'IND331022A1B': 0.0,
 'IND331001A1C': 0.0,
 'IND331023AAA': 0.0017364033202356373,
 'IND331304AAA': 0.0026682779456193356,
 'IND331507AAA': 0.0,
 'IND331701AAA': 0.0013353474320241694,
 'IND333001AAA': 0.0,
 'IND333028AAA': 0.0020120845921450152,
 'IND333031AAA': 0.0021329305135951663,
 'IND333042AAA': 0.0,
 'IND334001AAB': 0.00019979536111497918,
 'IND334001AAC': 0.004419335347432024,
 'IND332713AAA': 0.0008072507552870091,
 'IND332709AAA': 0.0,
 'IND332715AAB': 0.0,
 'IND333502AAA': 0.0,
 'IND333504AAA': 0.0012096700954779649,
 'IND334803AAA': 0.0013380234789821333,
 'IND341001AAC': 0.006504852605513141,
 'IND335001AAA': 0.0030574018126888207,
 'IND335051AAA': 0.0013380234789821329,
 'IND335803AAA': 0.0,
 'IND335804AAD': 0.0012000000000000001,
 'IND335701AAA': 0.00039959072222995836,
 'IND335703AAA': 0.0,
 'IND341030AAA': 0.0,
 'IND341303AAA': 0.007025981873111783,
 'IND341306AAA': 0.0066247734138972815,
 'IND341503AAB': 0.0,
 'IND341510AAB': 0.0,
 'IND341505AAA': 0.0008024169184290031,
 'IND342601AAA': 0.0,
 'IND342902A1B': 0.0,
 'IND342902AAA': 0.0,
 'IND344022AAB': 0.0016048338368580062,
 'IND342301AAA': 0.0,
 'IND343029AAB': 0.0016048338368580062,
 'IND344001AAA': 0.0008024169184290031,
 'IND345001AAA': 0.0,
 'IND345021AAA': 0.0,
 'IND360003AAA': 0.0,
 'IND360311AAA': 0.0,
 'IND360050AAA': 0.0,
 'IND360370AAA': 1.3319690740998613e-05,
 'IND360410AAA': 1.933534743202417e-05,
 'IND360490AAA': 1.2108809764544193e-05,
 'IND362001AAA': 8.096676737160121e-05,
 'IND360510AAB': 1.816321464681629e-05,
 'IND360530AAB': 2.5428500505542808e-05,
 'IND360575AAA': 1.0897928788089774e-05,
 'IND361001AAA': 0.0,
 'IND361305AAC': 3.632642929363258e-06,
 'IND361315AAA': 0.0,
 'IND361335AAA': 3.625377643504532e-06,
 'IND360002AAB': 0.0,
 'IND362220AAA': 7.265285858726516e-06,
 'IND362265AAA': 3.2628398791540785e-05,
 'IND362150AAA': 8.476166835180936e-06,
 'IND362225AAA': 0.0,
 'IND362720AAA': 2.4169184290030212e-05,
 'IND362560AAA': 1.570996978851964e-05,
 'IND363001AAA': 2.4217619529088387e-06,
 'IND363421AAB': 2.4169184290030213e-06,
 'IND363310AAB': 0.0026682779456193356,
 'IND363330AAB': 0.0,
 'IND364710AAA': 0.0,
 'IND363520AAC': 0.0,
 'IND363621AAB': 0.0,
 'IND363641AAA': 0.0,
 'IND364004AAB': 0.0012036253776435046,
 'IND365560AAA': 0.0008024169184290031,
 'IND364270AAA': 0.0,
 'IND364001AAA': 0.0,
 'IND364290AAA': 0.0,
 'IND365560AAB': 0.00040120845921450156,
 'IND370001AAA': 0.0013416561219114966,
 'IND370110AAA': 0.0,
 'IND370201AAA': 0.0034706948640483384,
 'IND370615AAB': 0.0,
 'IND380005AAA': 0.0007991814444599167,
 'IND382421AAA': 0.0,
 'IND382721AAA': 0.0,
 'IND380006AAA': 0.0,
 'IND380006AAB': 0.0,
 'IND380021AAA': 0.0,
 'IND380054AAA': 0.0,
 'IND380015AAB': 0.0,
 'IND382345AAA': 0.0,
 'IND384205AAA': 0.005732930513595166,
 'IND387620AAB': 0.00040120845921450156,
 'IND388320AAA': 0.0016241691842900302,
 'IND389001AAA': 0.0008024169184290031,
 'IND395023AAA': 0.011670391408065407,
 'IND382715AAA': 0.0,
 'IND383001AAA': 0.0008024169184290031,
 'IND383315AAC': 0.00040120845921450156,
 'IND383255AAB': 0.0,
 'IND384170AAA': 0.0012012084592145015,
 'IND384265AAB': 0.0008,
 'IND384355AAB': 0.0,
 'IND385001AAA': 0.00040120845921450156,
 'IND385320AAA': 0.0,
 'IND385340AAB': 0.0013353474320241692,
 'IND385535AAA': 0.0,
 'IND387001AAA': 0.0,
 'IND388220AAA': 0.0,
 'IND389230AAB': 0.0,
 'IND388121AAA': 0.00040120845921450156,
 'IND388620AAB': 0.0,
 'IND389151AAA': 0.00040201248418286723,
 'IND457661AAA': 0.0,
 'IND390018AAB': 0.0,
 'IND390020AAA': 0.0008024169184290031,
 'IND391110AAD': 0.0,
 'IND395001AAA': 0.0,
 'IND395023AAD': 2.7794561933534743e-05,
 'IND395004AAB': 0.0,
 'IND395006AAA': 0.0,
 'IND395009AAA': 0.0,
 'IND395010AAB': 0.0,
 'IND394221AAA': 0.0,
 'IND396191AAC': 0.0012036253776435046,
 'IND396445AAA': 6.054404882272096e-06,
 'IND396001AAA': 1.3319690740998613e-05,
 'IND396105AAA': 0.0,
 'IND396191AAB': 0.0,
 'IND396210AAA': 0.0,
 'IND396232AAA': 0.0,
 'IND396321AAA': 1.2108809764544193e-05,
 'IND396580AAB': 0.0,
 'IND400011AAA': 0.0004,
 'IND400072AAD': 0.00048826512862766645,
 'IND400015AAA': 0.0013365558912386704,
 'IND400015AAB': 0.0,
 'IND400016AAA': 0.0,
 'IND400016AAB': 0.0,
 'IND400037AAA': 0.0,
 'IND400072AAJ': 0.00040120845921450156,
 'IND400064AAB': 0.0,
 'IND400072AAA': 0.0,
 'IND400701AAB': 0.0,
 'IND401104AAA': 0.002140785498489426,
 'IND401104AAB': 0.0,
 'IND421302AAR': 0.0016084592145015108,
 'IND421302AAS': 0.0,
 'IND400072AAC': 0.0,
 'IND400072AAI': 0.0,
 'IND000000AFS': 0.0,
 'IND400102AAB': 0.0,
 'IND400102AAC': 0.00040120845921450156,
 'IND400052AAA': 0.0,
 'IND400612AAA': 0.0,
 'IND400705AAA': 0.0004008016032064128,
 'IND421302AAH': 0.0,
 'IND401208AAA': 0.0,
 'IND401209AAA': 0.0,
 'IND401209AAB': 0.0,
 'IND401501AAA': 0.0,
 'IND401602AAA': 0.0,
 'IND402107AAA': 0.0,
 'IND402109AAA': 0.0,
 'IND402301AAA': 0.0,
 'IND403002AAA': 0.0,
 'IND403726AAB': 0.0,
 'IND403401AAA': 0.0,
 'IND403507AAA': 0.0,
 'IND403507AAB': 0.0,
 'IND403601AAA': 0.0,
 'IND403702AAA': 0.0012399198183488233,
 'IND575004AAB': 0.013392104350835436,

In [34]:
community_df["community_id"].nunique()

94

In [35]:
community_df.groupby(
    "community_id"
)["facility"].count().describe()

count     94.000000
mean      17.627660
std       25.535126
min        2.000000
25%        3.000000
50%        5.000000
75%       19.750000
max      122.000000
Name: facility, dtype: float64

In [36]:
community_df.groupby(
    "community_id"
)["facility"].count().sort_values(
    ascending=False
).head(20)

community_id
1     122
60    109
53     98
10     83
22     73
15     71
82     67
37     64
75     64
7      58
45     50
28     49
0      43
44     42
34     40
76     35
89     31
79     29
67     28
58     25
Name: facility, dtype: int64

In [37]:
graph_feature_store.nlargest(
    20,
    "closeness_centrality"
)

,facility,degree_centrality,in_degree_centrality,out_degree_centrality,betweenness_centrality,closeness_centrality,pagerank,hub_score,authority_score,community_id,community_size
25,IND000000ACB,0.056763,0.027174,0.029589,0.220228,0.183963,0.011424,0.044913,0.034370,1,122
12,IND562132AAA,0.042874,0.021739,0.021135,0.124943,0.171499,0.009635,0.030917,0.028747,60,109
67,IND712311AAA,0.027778,0.014493,0.013285,0.090659,0.168480,0.006547,0.012106,0.018286,75,64
61,IND421302AAG,0.035024,0.017512,0.017512,0.069625,0.167048,0.006190,0.029250,0.024379,7,58
64,IND501359AAE,0.034420,0.018116,0.016304,0.092632,0.166713,0.008798,0.020057,0.021619,53,98
68,IND751002AAB,0.011473,0.007850,0.003623,0.021587,0.162575,0.002846,0.005323,0.013295,79,29
1,IND411033AAA,0.025966,0.013889,0.012077,0.043254,0.161800,0.006174,0.017202,0.019171,37,64
62,IND462022AAA,0.013285,0.007850,0.005435,0.029638,0.159997,0.004297,0.004994,0.014986,44,42
47,IND131028AAB,0.024155,0.012077,0.012077,0.047837,0.156051,0.005777,0.008607,0.016320,15,71
66,IND600056AAB,0.021739,0.010870,0.010870,0.042146,0.155466,0.004529,0.007809,0.010477,60,109
56,IND302014AAA,0.010870,0.006039,0.004831,0.040490,0.155143,0.002901,0.006163,0.008975,22,73
102,IND110037AAM,0.027174,0.012681,0.014493,0.041331,0.154629,0.004855,0.019398,0.014353,1,122
24,IND160002AAC,0.036836,0.019324,0.017512,0.055078,0.153548,0.008052,0.017644,0.014794,10,83
70,IND834002AAB,0.007246,0.003019,0.004227,0.007909,0.152171,0.001512,0.004503,0.009484,89,31
52,IND209304AAA,0.017512,0.009662,0.007850,0.040359,0.151862,0.005098,0.006106,0.009327,1,122
59,IND382430AAB,0.018116,0.010266,0.007850,0.031695,0.150515,0.003816,0.005194,0.011051,28,49
69,IND821115AAB,0.006643,0.003623,0.003019,0.009196,0.150243,0.002223,0.004757,0.006545,89,31
50,IND201301AAF,0.006643,0.004831,0.001812,0.001635,0.149792,0.002477,0.000011,0.008483,1,122
43,IND125001AAA,0.009058,0.004227,0.004831,0.008984,0.147921,0.002910,0.005698,0.007509,8,21
49,IND201007AAA,0.007850,0.004831,0.003019,0.003771,0.147921,0.002298,0.000022,0.008484,1,122

In [38]:
graph_feature_store.nlargest(
    20,
    "hub_score"
)

,facility,degree_centrality,in_degree_centrality,out_degree_centrality,betweenness_centrality,closeness_centrality,pagerank,hub_score,authority_score,community_id,community_size
25,IND000000ACB,0.056763,0.027174,0.029589,0.220228,0.183963,0.011424,0.044913,0.034370,1,122
12,IND562132AAA,0.042874,0.021739,0.021135,0.124943,0.171499,0.009635,0.030917,0.028747,60,109
61,IND421302AAG,0.035024,0.017512,0.017512,0.069625,0.167048,0.006190,0.029250,0.024379,7,58
64,IND501359AAE,0.034420,0.018116,0.016304,0.092632,0.166713,0.008798,0.020057,0.021619,53,98
102,IND110037AAM,0.027174,0.012681,0.014493,0.041331,0.154629,0.004855,0.019398,0.014353,1,122
24,IND160002AAC,0.036836,0.019324,0.017512,0.055078,0.153548,0.008052,0.017644,0.014794,10,83
1,IND411033AAA,0.025966,0.013889,0.012077,0.043254,0.161800,0.006174,0.017202,0.019171,37,64
67,IND712311AAA,0.027778,0.014493,0.013285,0.090659,0.168480,0.006547,0.012106,0.018286,75,64
583,IND395023AAA,0.009662,0.004831,0.004831,0.013667,0.146183,0.001928,0.011188,0.007899,37,64
1022,IND560099AAB,0.017512,0.006643,0.010870,0.003475,0.138433,0.002242,0.010858,0.007739,60,109
114,IND110044AAB,0.004831,0.001208,0.003623,0.002606,0.109616,0.000385,0.009236,0.000304,1,122
47,IND131028AAB,0.024155,0.012077,0.012077,0.047837,0.156051,0.005777,0.008607,0.016320,15,71
1039,IND560300AAA,0.009662,0.002415,0.007246,0.005632,0.137060,0.000952,0.008081,0.004596,60,109
66,IND600056AAB,0.021739,0.010870,0.010870,0.042146,0.155466,0.004529,0.007809,0.010477,60,109
93,IND400072AAB,0.013285,0.006643,0.006643,0.005097,0.138561,0.001784,0.007377,0.007137,7,58
74,IND000000ACT,0.001812,0.000000,0.001812,0.000000,0.000000,0.000118,0.006887,-0.000000,15,71
683,IND580028AAA,0.010266,0.005435,0.004831,0.013632,0.138896,0.003565,0.006233,0.005644,34,40
56,IND302014AAA,0.010870,0.006039,0.004831,0.040490,0.155143,0.002901,0.006163,0.008975,22,73
52,IND209304AAA,0.017512,0.009662,0.007850,0.040359,0.151862,0.005098,0.006106,0.009327,1,122
882,IND518002AAA,0.010870,0.006039,0.004831,0.010051,0.140596,0.002721,0.005719,0.006062,57,15

In [39]:
graph_feature_store.nlargest(
    20,
    "authority_score"
)

,facility,degree_centrality,in_degree_centrality,out_degree_centrality,betweenness_centrality,closeness_centrality,pagerank,hub_score,authority_score,community_id,community_size
25,IND000000ACB,0.056763,0.027174,0.029589,0.220228,0.183963,0.011424,0.044913,0.034370,1,122
12,IND562132AAA,0.042874,0.021739,0.021135,0.124943,0.171499,0.009635,0.030917,0.028747,60,109
61,IND421302AAG,0.035024,0.017512,0.017512,0.069625,0.167048,0.006190,0.029250,0.024379,7,58
64,IND501359AAE,0.034420,0.018116,0.016304,0.092632,0.166713,0.008798,0.020057,0.021619,53,98
1,IND411033AAA,0.025966,0.013889,0.012077,0.043254,0.161800,0.006174,0.017202,0.019171,37,64
67,IND712311AAA,0.027778,0.014493,0.013285,0.090659,0.168480,0.006547,0.012106,0.018286,75,64
47,IND131028AAB,0.024155,0.012077,0.012077,0.047837,0.156051,0.005777,0.008607,0.016320,15,71
62,IND462022AAA,0.013285,0.007850,0.005435,0.029638,0.159997,0.004297,0.004994,0.014986,44,42
24,IND160002AAC,0.036836,0.019324,0.017512,0.055078,0.153548,0.008052,0.017644,0.014794,10,83
102,IND110037AAM,0.027174,0.012681,0.014493,0.041331,0.154629,0.004855,0.019398,0.014353,1,122
68,IND751002AAB,0.011473,0.007850,0.003623,0.021587,0.162575,0.002846,0.005323,0.013295,79,29
59,IND382430AAB,0.018116,0.010266,0.007850,0.031695,0.150515,0.003816,0.005194,0.011051,28,49
66,IND600056AAB,0.021739,0.010870,0.010870,0.042146,0.155466,0.004529,0.007809,0.010477,60,109
70,IND834002AAB,0.007246,0.003019,0.004227,0.007909,0.152171,0.001512,0.004503,0.009484,89,31
52,IND209304AAA,0.017512,0.009662,0.007850,0.040359,0.151862,0.005098,0.006106,0.009327,1,122
56,IND302014AAA,0.010870,0.006039,0.004831,0.040490,0.155143,0.002901,0.006163,0.008975,22,73
49,IND201007AAA,0.007850,0.004831,0.003019,0.003771,0.147921,0.002298,0.000022,0.008484,1,122
50,IND201301AAF,0.006643,0.004831,0.001812,0.001635,0.149792,0.002477,0.000011,0.008483,1,122
53,IND282002AAD,0.006643,0.003623,0.003019,0.004669,0.147658,0.001305,0.002240,0.008090,1,122
583,IND395023AAA,0.009662,0.004831,0.004831,0.013667,0.146183,0.001928,0.011188,0.007899,37,64